esphome:
  name: esp32-c3-ili
  friendly_name: esp32-c3-ili

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "N1FaEsACNQ/ovjnXwGpnPHK7GXxw3QAAF65BcCSp3Zs="

ota:
  password: "15b562710e1e4093db0db97241637392"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-C3-Ili Fallback Hotspot"
    password: "5A7wjKFbhSBH"

captive_portal:

#these are the SPI pins for the controller
spi:
  clk_pin: 6
  mosi_pin: 7
  miso_pin: 2

color:
  - id: BLACK
    red: 0%
    green: 0%
    blue: 0% 
  - id: RED
    red: 100%
    green: 3%
    blue: 5%  

display:
  - platform: ili9xxx
    model: ili9341
    dc_pin: 4
    cs_pin: 1
    rotation: 0
    reset_pin: 10
    lambda: |-
      it.fill(BLACK);
      if (id(ilitouch).touched)
        it.filled_circle(id(ilitouch).x, id(ilitouch).y, 10, RED);
    
 
touchscreen:
  platform: xpt2046
  id: ilitouch
  cs_pin: 0
  swap_x_y: false
  calibration_x_min: 467
  calibration_x_max: 3599
  calibration_y_min: 3808
  calibration_y_max: 467
  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%d",
              id(ilitouch).x,
              id(ilitouch).y,
              id(ilitouch).x_raw,
              id(ilitouch).y_raw
              );

output:
  - platform: ledc
    pin: 5
    id: tft_backlight

# Example usage in a light
light:
  - platform: monochromatic
    output: tft_backlight
    internal: true
    restore_mode: ALWAYS_ON